### ISSUE TITLE
Setup publishing to Maven Central

### ISSUE THREAD

**Issue by steve-todorov** [uploadcare/uploadcare-android#55]
# Task Description

We used to publish our artifacts to JCenter. Unfortunately, as of May 2021 package publications to JCenter have been halted as part of the plan to sunset the JCenter service ([more here](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)). 

As a result, we need to start publishing our artifacts to Maven Central instead of JCenter.

# Tasks

The following tasks will need to be carried out:

* [x] Investigate the current state of the code.
* [x] Plan what needs to be done and append it to the list.
* [x] Raise request for access from Sonatype.
  * [x] Raised [OSSRH-92853](https://issues.sonatype.org/browse/OSSRH-92853) , also related to [OSSRH-12978](https://issues.sonatype.org/browse/OSSRH-12978).
* [x] Receive necessary access.
* [x] Create new GPG keys and publish them.
* [x] Setup publishing in gradle build scripts (using the new GPG keys)
  * [x] Public key has been published at https://keyserver.ubuntu.com/ (key id: `A0835D6B27223852`)
* [x] Create a build pipeline (builds pull requests).
* [x] Create a deploy pipeline which builds, signs and deploys artifacts from a tagged release to Maven Central.

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: 
  * #48
  * #46 

# Useful Links

* [OSS Sonatype](https://oss.sonatype.org/)
* [JCenter sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)
* [Gradle publishing](https://docs.gradle.org/current/userguide/publishing_maven.html)

# Help

* Points of contact:
  * @carlspring
  * @steve-todorov
  * @rsedykh
