### ISSUE TITLE
Set up a CodeQL Github Workflow

### ISSUE THREAD

**Issue by carlspring** [uploadcare/uploadcare-android#64]
# Task Description

Set up a CodeQL Github Workflow that checks for vulnerabilities in the existing code and pull requests.

# Tasks

The following tasks will need to be carried out:

* [x] Add daily cron task that runs at 08:30.
* [x] Add a check against pull requests based on the `master`.
* [x] Add a check on push against the `master`.

# Task Relationships

This task:
* Is a sub-task of:
* Depends on:
* Is a follow-up of:
* Relates to:

# Useful Links

# Help

* Points of contact:
  * @carlspring
  * @steve-todorov
